### ISSUE TITLE
try clamp_min(0.001)  to avoid nan when backward() in early step

### ISSUE THREAD

**Issue by vegetable09** [One-sixth/ms_ssim_pytorch#3]
thanks for your great effort to speed up the msssim.

I found nan when backward in very early iter when training. this is because

`cs**a => 1/cx**(a-1) when backward`

in the early step, the cs is very small, so 1/cs is inf.

I noticed that you use clamp_min(0.) in the msssim.py. I think replace 0 with 0.00001 will fix the nan problem when early train.
```

        ssim_val = ssim_val.clamp_min(0.0001) # avoid 1/x**(a-1) to be inf when x is very close to zero
        cs = cs.clamp_min(0.0001)
```

please correct me if i am wrong

**Comment by vegetable09** [comment]
but i have not test why ssim_map still negative while cs_map is already clamp(min=0)

**Comment by One-sixth** [comment]
Thank you for finding the bug, your solution is very effective, the code has been updated.
