### ISSUE TITLE
X = F.avg_pool2d(X, kernel_size=2, stride=2, ceil_mode=True)

### ISSUE THREAD

**Issue by s0966066980** [One-sixth/ms_ssim_pytorch#5]
https://github.com/One-sixth/ms_ssim_pytorch/blob/6269c62e0dd29c91fa38e4ba73d906d0c84ca966/ssim.py#L115
Stride=2 will cause problems, will it affect if it is changed to 1?

**Comment by One-sixth** [comment]
Hello. 
If you need to use the default version of MS-SSIM, please make sure that the input image size is greater than 176x176.
For ms-ssim, stride=2 is required. Of course, you can modify it as you want, as long as you know what you need.

**Comment by s0966066980** [comment]
ok, I didn't notice the image size! thank you your response!

**Comment by One-sixth** [comment]
close.
